on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          submodules: "true"
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci --include=optional
        if: ${{ steps.release.outputs.release_created }}
      - run: npm run build
        if: ${{ steps.release.outputs.release_created }}
        
      - name: Publish core to npm
        run: cd packages/core && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
        continue-on-error: true
      - name: Publish addons to npm
        run: cd packages/addons && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
        continue-on-error: true
      - name: Publish forms to npm
        run: cd packages/forms && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
        continue-on-error: true
      - name: Publish wizards to npm
        run: cd packages/wizards && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
        continue-on-error: true
      - name: Publish xml to npm
        run: cd packages/xml && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
        continue-on-error: true
      - name: Publish plugins to npm
        run: cd packages/plugins && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
        continue-on-error: true
      - name: Publish open-scd to npm
        run: cd packages/openscd && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
        continue-on-error: true
      
        
      - name: Create and Zip Build Assets
        if: ${{ steps.release.outputs.release_created }}
        run: | 
          zip -r open-scd.zip ./packages/distribution/build/
          tar -czvf open-scd.tar.gz ./packages/distribution/build/

      - name: Upload Build Assets
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:  gh release upload ${{ steps.release.outputs.tag_name }} open-scd.zip open-scd.tar.gz